### ISSUE TITLE
Inputs need de-questioning before cleaning

### ISSUE THREAD

**Issue by fileunderjeff** [fileunderjeff/houston-city-council-transcripts#3]
I will set up a master csv with TOPIC / QUESTION / CANDIDATE / RESPONSE in one table. I can also set up a question-scrubbed version of the candidate transcripts.

**Comment by neerajt** [comment]
Question-scrubbing can be done in `R/0-prep_data.R - it'll still be good to have a file per candidate of everything that candidate said, right?

**Comment by fileunderjeff** [comment]
Yes, absolutely. I'll hold off on the manual scrubbing. Thanks!
